import { NextRequest, NextResponse } from 'next/server'
import { serviceClient } from '@/lib/supabase'
import type { Bundle, Skill } from '@/lib/types'

/**
 * GET /api/bundles/:id.md — returns bundle as merged markdown (agent-friendly)
 * This is the correct URL for the curl install command shown on the bundles page.
 */
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  let { id } = await params
  // Strip .md suffix if passed directly
  if (id.endsWith('.md')) id = id.slice(0, -3)

  const { data: bundle, error } = await serviceClient
    .from('bundles')
    .select('*')
    .eq('id', id)
    .single()

  if (error || !bundle) {
    return new NextResponse('# Bundle not found\n', {
      status: 404,
      headers: { 'Content-Type': 'text/markdown; charset=utf-8' },
    })
  }

  const b = bundle as Bundle

  // Fetch all skills in this bundle
  const { data: skills } = await serviceClient
    .from('skills')
    .select('id, name, ecosystem, content')
    .in('id', b.skills)

  const BASE = 'https://agentrel.vercel.app'

  const lines: string[] = [
    `# ${b.name}`,
    '',
    b.description ? `> ${b.description}` : '',
    '',
    `**Skills included:** ${(skills ?? []).length}`,
    `**Bundle URL:** ${BASE}/api/bundles/${id}.md`,
    '',
    '---',
    '',
  ]

  // Merge all skill content
  for (const skill of (skills ?? []) as Skill[]) {
    lines.push(`## ${skill.name}`)
    lines.push(`> Skill ID: \`${skill.id}\` · Ecosystem: ${skill.ecosystem}`)
    lines.push(`> Direct URL: ${BASE}/api/skills/${skill.id}.md`)
    lines.push('')
    if (skill.content) {
      // Strip frontmatter if present
      const content = skill.content.replace(/^---[\s\S]*?---\n?/, '').trim()
      lines.push(content)
    }
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  lines.push(`*Bundle generated by AgentRel · ${new Date().toISOString().slice(0, 10)}*`)

  return new NextResponse(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  })
}
