import { NextResponse } from 'next/server'
import { serviceClient } from '@/lib/supabase'

export const revalidate = 3600  // regenerate every hour

export async function GET() {
  const { data: skills, error } = await serviceClient
    .from('skills')
    .select('id, name, ecosystem, type, access')
    .order('ecosystem', { ascending: true })
    .order('name', { ascending: true })

  if (error) {
    return new NextResponse(`# AgentRel Skill Index\n\nError loading skills: ${error.message}`, {
      status: 500,
      headers: { 'Content-Type': 'text/markdown; charset=utf-8' },
    })
  }

  // Group by ecosystem
  const grouped: Record<string, typeof skills> = {}
  for (const skill of skills ?? []) {
    const eco = skill.ecosystem || 'general'
    if (!grouped[eco]) grouped[eco] = []
    grouped[eco].push(skill)
  }

  // Ecosystem display names
  const ECO_LABELS: Record<string, string> = {
    ethereum: 'Ethereum / EVM',
    solana: 'Solana',
    monad: 'Monad',
    zama: 'Zama / fhEVM',
    near: 'NEAR',
    cosmos: 'Cosmos / IBC',
    polkadot: 'Polkadot / Substrate',
    hyperliquid: 'Hyperliquid',
    kite: 'Kite AI',
    '0g': '0G Network',
    bittensor: 'Bittensor',
    virtuals: 'Virtuals Protocol',
    sentient: 'Sentient',
    aptos: 'Aptos',
    standards: 'EVM Standards (ERC/EIP)',
    security: 'Security',
    'dev-tooling': 'Dev Tooling',
    grants: 'Grants & Funding',
    bounty: 'Bounties & Hackathons',
    hackathon: 'Active Hackathons',
    cryptoskills: 'Cross-chain Protocols',
    general: 'General',
  }

  const BASE_URL = 'https://agentrel.vercel.app'

  const lines: string[] = [
    '# AgentRel — Web3 AI Skills Index',
    '',
    `> ${skills?.length ?? 0} Skills across ${Object.keys(grouped).length} ecosystems`,
    `> Base URL: ${BASE_URL}/api/skills/{skill-id}.md`,
    `> Updated: ${new Date().toISOString().slice(0, 10)}`,
    '',
    '## How to Use',
    '',
    '```bash',
    '# Fetch any skill directly',
    `curl "${BASE_URL}/api/skills/monad/network-config.md"`,
    '',
    '# List skills by ecosystem',
    `curl "${BASE_URL}/api/skills?ecosystem=ethereum&limit=20"`,
    '```',
    '',
    '---',
    '',
  ]

  // Sort ecosystems: known ones first, then alphabetical
  const ECO_ORDER = [
    'ethereum', 'solana', 'monad', 'zama', 'standards', 'security',
    'bittensor', 'hyperliquid', 'kite', '0g', 'virtuals', 'sentient',
    'aptos', 'near', 'cosmos', 'polkadot', 'dev-tooling', 'grants',
    'bounty', 'hackathon', 'cryptoskills', 'general',
  ]
  const sortedEcos = [
    ...ECO_ORDER.filter(e => grouped[e]),
    ...Object.keys(grouped).filter(e => !ECO_ORDER.includes(e)).sort(),
  ]

  for (const eco of sortedEcos) {
    const ecoSkills = grouped[eco]
    const label = ECO_LABELS[eco] ?? eco.charAt(0).toUpperCase() + eco.slice(1)
    lines.push(`## ${label}`)
    lines.push('')
    for (const skill of ecoSkills) {
      const url = `${BASE_URL}/api/skills/${skill.id}.md`
      const accessTag = skill.access && skill.access !== 'free' ? ` *(${skill.access})*` : ''
      lines.push(`- [${skill.name}](${url})${accessTag}`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push(`*Generated by AgentRel · ${BASE_URL}*`)

  const md = lines.join('\n')
  return new NextResponse(md, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  })
}
